### ISSUE TITLE
Step 5 AKS setup

### ISSUE THREAD

**Issue by jgezelscorp** [mattmcspirit/hybridworkshop#11]
Hi

I made it to step 5 but when setting up the AKS cluster, the steps point to the InternalNAT switch. I can only select the Compute switch but I get the error that there is no interface connected on. (I guess because of it being a type Internal)

I could setup a new vSwitch (type Extended) but that seems to mess up things with the management adapter.

What am I missing?

**Comment by mattmcspirit** [comment]
Hi - you're trying to deploy the AKS pieces on the nested HCI cluster, which isn't advised for performance reasons - the guidance advises you to deploy to the Windows Server 2019 VM host itself, instead of the the HCI cluster.

![image](https://user-images.githubusercontent.com/20191274/135934333-9619f1a5-f40d-41c4-9ff9-c24014e416ae.png)

https://github.com/mattmcspirit/hybridworkshop/blob/main/steps/5_DeployAKSHCI.md#deploying-the-aks-on-azure-stack-hci-management-cluster

Hope that helps!
Matt

**Comment by jgezelscorp** [comment]
Ok, got it! Thanks

**Comment by jgezelscorp** [comment]
Hey Matt

By the way, in the Wizard when deploying AKS on the host itself, I got an error when enabling the Credential delegation.
I had to add an SPN on the server: WSMAN/hybridhost001.hybrid.local

Not sure if it me or .... But it passed so good stuff....

Regards

Jan

**Comment by mattmcspirit** [comment]
Thanks for this - can you confirm if you did this too?

Enable CredSSP in Windows Admin Center
NOTE - if you receive a WinRM error, open an Administrative PowerShell console and run the following command and then retry:

![image](https://user-images.githubusercontent.com/20191274/136055083-853cb80a-76d5-4a0b-bce5-f9d4cf9c29a3.png)

Restart-Service WinRm -Force

Just wanted to check if i need to add additional troubleshooting.

Thanks!

**Comment by jgezelscorp** [comment]
Lol, I went straight to troubleshooting the issue and when I added the SPN manual and continued the lab, I saw that it was marked. (if issues execute Restart-Service WinRM -force)
So, I'm quite sure that the service restart would create the entry that I've put in manually ....

We will do a session within a few weeks based on your workshop with our partners so I'll probably come back with the test !

Thanks again, awesome work.
